### PR TITLE
fixes #17

### LINKED ISSUE #17: Not properly updating schema when new array is added
Whenever you add an array to the schema of an existing table, it will try to add the columns without creating the table first which will give these errors : 
[TARGET] [INFO] [`product_collections`] Adding column `product_collections`._root_id Int64
[TARGET] [INFO] [`product_collections`] Adding column `product_collections`._level_0_index Int32
[TARGET] [INFO] [`product_collections`] Adding column `product_collections`._parent_id Int64
Unknown error field: Code: 60. DB::Exception: Could not find table: product_collections. (UNKNOWN_TABLE) (version 24.1.5.6 (official build))
[TARGET] [WARN] query sql failed [ALTER TABLE `product_collections`
ADD COLUMN `_parent_id` Int64]: Code: 60. DB::Exception: Could not find table: product_collections. (UNKNOWN_TABLE) (version 24.1.5.6 (official build))

### PR DESCRIPTION
**Pull request by nmorvil**
fixes #17

### CODE REVIEW

File: src/jsonSchemaTranslator.ts [hunk 1]
```diff
@@ -142,6 +142,9 @@ export async function updateSchema(meta: ISourceMeta, ch: ClickhouseConnection)
   await Promise.all(meta.children.map((child) => updateSchema(child, ch)))
 
   const isRoot = meta.pkMappings.filter((pkMap) => pkMap.pkType === PKType.ROOT).length == 0
+  if (!(await ch.listTables()).includes(meta.sqlTableName.slice(1, meta.sqlTableName.length - 1))) {
```
Comment (Yuruh) [inline src/jsonSchemaTranslator.ts:145]: To avoid making the same call several times, we could use the list `existingTables` available in `createStreamProcessor`

Comment (Yuruh) [inline src/jsonSchemaTranslator.ts:145]: To remove backquotes, a method `unescape` is available, to export from `jsonSchemaTranslator`

**Review by Yuruh — CHANGES_REQUESTED** [review]

**Review by Yuruh — APPROVED** [review]
